build.gradle
=> updating version to 3.2.0

KalturaWowzaServer/src/com/kaltura/media/server/wowza/RecordingManager.java
remove EntryRecorder from recorders map
removeListener on unPublish
stopRecording on unPublish
=> fix memory leak

build.gradle
change version
3.0.9-PLAT-2504
=> change version

KalturaMediaServer/src/com/kaltura/media/server/api/KalturaWebServicesServer.java, KalturaMediaServer/src/com/kaltura/media/server/managers/KalturaCuePointsManager.java
PLAT-2666
Iterating over collections while deleting entries from them
Created Concurrent Modification Exception
Using iterator to avoid exception
=> Concurrent Modification Exception PLAT-2666

KalturaWowzaServer/build.gradle, build.gradle
=> change version, added artifacts location to log

KalturaWowzaServer/build.gradle
=> copying artifacts to a folder in KalturaWowzaServer build dir

KalturaMediaServer/src/main/java/com/kaltura/media/server/KalturaServer.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/KalturaManager.java, build.gradle
=> Refactoring due to client lib changes

KalturaWowzaServer/release/build.xml, KalturaWowzaServer/release/configure.xsl
- added support for eCDN specific ini file to build.xml
- fixed some ant parser errors in configure.xsl
=> Dev plat 2848

KalturaMediaServer/src/main/java/com/kaltura/media/server/KalturaServer.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/KalturaUncaughtExceptionHnadler.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/api/services/KalturaCuePointsService.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/KalturaCuePointsManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/CuePointsManager.java
=> Adding informative logs for ad stitching and fixing bugs

build.gradle
=> changing client lib version (downgrading commons-codec to 1.4)

KalturaWowzaServer/release/configure.xsl
change dvrChunkDurationMinimum from 10000 to 9999
3.0.11-PLAT-2497
=> workaround for DVR multi bitrate issues

KalturaWowzaServer/release/build.xml
delete files in wowza lib dir based on pattern string
=> PLAT-2939. 

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/RecordingManager.java
=> memory leak regression - insert memory leak fix

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
=> Remove PacketListener until high CPU investigation is completed

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/CuePointsManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
Return the input validation back to the code
PLAT-3035
=> Fix isLive true in case of constant sync points.

release.php
=> Update release.php script to publish artifacts in the agreed structure

KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/KalturaLiveChannelManager.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/KalturaLiveManager.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/KalturaLiveStreamManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/CuePointsManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
Mark the time the stream started (according to the primary Wowza)
Calculate offset according to the stream start time
PLAT-2868
=> Fix offset calculation

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/CuePointsManager.java
=> Fix offset calculation and add additional logs

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
disconnect the session.
#SUP-4598 #0.5 day
=> Input validation - in case an unexpected stream is being ingested -

Utils/automation/tasks/build.gradle
=> remove application plugin

Utils/automation/tasks/build.gradle, Utils/automation/tasks/src/main/java/tests/MultiBitrateSyncTest.java
=> remove workaround for specific wowza

Utils/automation/tasks/build.gradle
=> remove output logs

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/SmilManager.java
=> Avoid concurrent modification

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/PushPublishManager.java
=> Removing referrer on unPublish

Utils/automation/comparators/src/main/java/comparators/imagemagik/ImageMagikComparator.java, Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloader.java, Utils/automation/tasks/build.gradle, Utils/automation/tasks/src/main/java/tasks/TsComparator.java
comparator will fail only if there are 3 subsequent failed ts file.
PLAT-3083
=> improve TsComparator

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/ZombieStreamsWatcher.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
=> Added Zombie streams watcher

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/CuePointsManager.java
remove redundant data and use a json parser
PLAT-3304
=> Optimize sync points ID3 tags generation

build.gradle
=> Enforcing java version before compilation

Utils/automation/stream-downloader/src/main/java/downloaders/StreamDownloader.java, Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloader.java, Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloaderWorker.java, Utils/automation/tasks/src/main/java/tasks/StatusWatcher.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/DirectoryWatcher.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryComparator.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryDownloader.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryTsComparatorFileHandler.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/FileHandlerIfc.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/SystemMonitor.java
=> Override revert

Utils/automation/stream-downloader/src/main/java/downloaders/hls/DVRInputStreamEnhancer.java, Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloader.java, Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloaderWorker.java, Utils/automation/stream-downloader/src/main/java/downloaders/hls/PlaylistEnhancer.java, Utils/automation/tasks/src/main/java/tasks/PartnerMonitor.java
=> Download live stream in addition to the DVR stream

Utils/automation/tasks/src/main/java/tasks/PartnerMonitor.java
=> change partner monitor to download stream correctly

Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryDownloader.java
=> system monitor downloads input and DVR streams

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/ZombieStreamsWatcher.java
=> Follow Wowza recomendation about zombie streams killing.

Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloader.java, Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloaderWorker.java, Utils/automation/tasks/src/main/java/configurations/TestConfig.java, Utils/automation/tasks/src/main/java/tasks/PartnerMonitor.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryDownloader.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryTsComparatorFileHandler.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/SystemMonitor.java, Utils/automation/tasks/src/main/resources/test-conf.json.template
=> Added run-forever support for sync entries (WN)

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
=> extract input validation to its own thread.

Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloaderWorker.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryComparator.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/EntryDownloader.java, Utils/automation/tasks/src/main/java/tasks/systemmonitor/SystemMonitor.java
1. Add directory per session (start time) under entry
2. Add time stamp to iter name
#PLAT-3524 #time 20m
=> System Monitor enhancments

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
properties
#PLAT-3531 #time 1h
=> Avoid Null pointer exception in case connection has no connection

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
=> Added rejection for requests with no request params

Utils/automation/stream-downloader/src/main/java/downloaders/hls/HLSDownloaderWorker.java
=> Added sub folder for each 1000 files

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java
=> remove source validation

README.md
few language changes to better reflect the project
=> minor language changes

Utils/automation/tasks/src/main/resources/test-conf.json.template
=> fix CI failures

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/ModuleRTMPPublishDebug.java
=> add RTMP logging module

KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/CuePointsManager.java
=> remove processSendDirectMessages()

KalturaWowzaServer/release/configure.xsl, KalturaWowzaServer/release/register_media_server.php
@kalturaguy , as approved, new pull against 4.3.1
=> 4.3.0 plat 4020

KalturaMediaServer/src/main/java/com/kaltura/media/server/KalturaServer.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/events/KalturaMetadataEvent.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/events/KalturaStreamEvent.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/ILiveManager.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/ILiveStreamManager.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/KalturaLiveManager.java, KalturaMediaServer/src/main/java/com/kaltura/media/server/managers/KalturaLiveStreamManager.java, KalturaRed5Server/WEB-INF/src/com/kaltura/media/server/red5/LiveStreamManager.java, KalturaRed5Server/WEB-INF/src/com/kaltura/media/server/red5/listeners/LiveStreamEntry.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/LiveChannelManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/LiveStreamManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/PushPublishManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/RecordingManager.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/events/KalturaMediaStreamEvent.java, KalturaWowzaServer/src/main/java/com/kaltura/media/server/wowza/listeners/LiveStreamEntry.java, Utils/automation/build.gradle, build.gradle
Reverts kaltura/media-server#280
=> Revert "4.3.3"

KalturaWowzaServer/src/main/java/com/kaltura/media_server/modules/LiveStreamSettingsModule.java
=> PLAT-7014 fix PTS misalignment calculation

KalturaWowzaServer/src/main/java/com/kaltura/media_server/modules/LiveStreamSettingsModule.java
Enhanced log messages for PTS sync monitoring
=> Enhanced log messages for PTS sync

KalturaWowzaServer/README.md, KalturaWowzaServer/build.gradle
=> support KalturaClient-3.3.4.jar

KalturaWowzaServer/src/main/java/com/kaltura/media_server/modules/RecordingModule.java, KalturaWowzaServer/src/main/java/com/kaltura/media_server/services/KalturaAPI.java
added new log messages in this merge
=> PLAT-7163 Distinguish old recording to new

KalturaWowzaServer/src/main/java/com/kaltura/media_server/modules/TemplateControlModule.java, KalturaWowzaServer/src/main/java/com/kaltura/media_server/services/DiagnosticsProvider.java
encoder data is displayed in diagnostics/entries
=> minor update to support encoder data in diagnostics

KalturaWowzaServer/src/main/java/com/kaltura/media_server/services/KalturaAPI.java, KalturaWowzaServer/src/main/java/com/kaltura/media_server/services/Utils.java
=> PLAT-6680: Resolve get_hostname on DNS machines
